version: 2

updates:
  - package-ecosystem: npm
    versioning-strategy: increase
    directory: "/"
    open-pull-requests-limit: 10

    schedule:
      interval: daily
      time: "07:00"
      timezone: Asia/Jakarta

    assignees:
      - manferlo81

    groups:
      rollup:
        dependency-type: production
        update-types:
          - minor
          - patch
        patterns:
          - rollup
          - "@rollup/plugin-*"
          - rollup-plugin-*

      eslint:
        dependency-type: development
        update-types:
          - minor
          - patch
        patterns:
          - eslint
          - globals
          - typescript-eslint
          - eslint-plugin-*
          - "@*/eslint-plugin"
          - "@eslint/*"
          - eslint-*

      test:
        dependency-type: development
        update-types:
          - minor
          - patch
        patterns:
          - jest
          - ts-jest

      babel:
        update-types:
          - minor
          - patch
        patterns:
          - "@babel/*"
          - core-js

      types:
        dependency-type: development
        update-types:
          - minor
          - patch
        patterns:
          - "@types/*"

      others:
        dependency-type: development
        update-types:
          - minor
          - patch
        patterns:
          - rimraf
          - husky
          - chokidar
          - npm-run-all
          - standard-version
