version: 2

updates:
  - package-ecosystem: npm
    versioning-strategy: increase
    directory: "/"
    open-pull-requests-limit: 10

    schedule:
      interval: daily
      time: "07:00"
      timezone: Asia/Jakarta

    assignees:
      - manferlo81

    groups:
      eslint:
        dependency-type: development
        patterns:
          - eslint
          - "@eslint/*"
          - eslint-plugin-*
          - "@*/eslint-plugin"
          - typescript-eslint
          - globals

      test:
        dependency-type: development
        patterns:
          - jest
          - ts-jest

      babel:
        patterns:
          - "@babel/*"
          - core-js

      types:
        dependency-type: development
        patterns:
          - "@types/*"

      others:
        dependency-type: development
        patterns:
          - husky
          - npm-run-all
          - rimraf
          - chokidar
