version: 2.1

orbs:
  codecov: codecov/codecov@1.2.3

executors:
  exec_node_20:
    docker:
      - image: cimg/node:20.15.1
    working_directory: ~/bundlib

commands:
  cmd_checkout_cache_and_install:
    steps:
      - checkout
      - restore_cache:
          keys:
            - v8-deps-bundlib-{{ checksum "package-lock.json" }}
            - v8-deps-bundlib-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v8-deps-bundlib-{{ checksum "package-lock.json" }}

  cmd_npm_publish:
    steps:
      - run:
          name: Login to npm
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - run:
          name: Publish to npm
          command: npm publish

jobs:
  job_test_and_build:
    executor: exec_node_20
    steps:
      - cmd_checkout_cache_and_install
      - run:
          name: Test
          command: npm test
      - run:
          name: Build
          command: npm run build
      - store_artifacts:
          path: dist
      - persist_to_workspace:
          root: ~/bundlib
          paths:
            - bin
            - dist
            - coverage

  job_upload_coverage:
    description: Upload coverage to Codecov
    executor: exec_node_20
    steps:
      - attach_workspace:
          at: ~/bundlib
      - codecov/upload:
          file: coverage/*.json

  job_publish_to_npm:
    description: Publish package to npm
    executor: exec_node_20
    steps:
      - attach_workspace:
          at: /
      - cmd_npm_publish

workflows:
  workflow_ci:
    jobs:
      - job_test_and_build:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/

      - job_upload_coverage:
          requires:
            - job_test_and_build
          filters:
            branches:
              only: /master/

      - job_publish_to_npm:
          context: npm
          requires:
            - job_test_and_build
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
