version: 2.1

orbs:
  codecov: codecov/codecov@1.2.3

executors:
  executor_node:
    docker:
      - image: cimg/node:22.3.0
    working_directory: ~/bundlib

commands:
  npm_publish:
    steps:
      - run:
          name: Login to npm
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - run:
          name: Publish to npm
          command: npm publish

jobs:
  test_and_build:
    executor: executor_node
    steps:
      - checkout
      - restore_cache:
          keys:
            - v7-deps-bundlib-{{ checksum "package.json" }}
            - v7-deps-bundlib-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v7-deps-bundlib-{{ checksum "package.json" }}
      - run:
          name: Test
          command: npm test
      - run:
          name: Build
          command: npm run build
      - persist_to_workspace:
          root: ~/bundlib
          paths: .

  upload_coverage:
    executor: executor_node
    steps:
      - attach_workspace:
          at: ~/bundlib
      - codecov/upload:
          file: coverage/*.json

  publish_to_npm:
    executor: executor_node
    steps:
      - attach_workspace:
          at: ~/bundlib
      - npm_publish

workflows:
  version: 2

  workflow:
    jobs:
      - test_and_build:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/

      - upload_coverage:
          requires:
            - test_and_build
          filters:
            branches:
              only: /master/

      - publish_to_npm:
          context: npm
          requires:
            - test_and_build
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
