version: 2.1

orbs:
  codecov: codecov/codecov@4.1.0

executors:
  executor_node_18:
    docker:
      - image: cimg/node:18.20
    working_directory: ~/bundlib

  executor_node_20:
    docker:
      - image: cimg/node:20.15.1
    working_directory: ~/bundlib

commands:
  command_ci:
    parameters:
      cache_key:
        type: string
        default: deps-bundlib
    steps:
      - checkout
      - restore_cache:
          keys:
            - << parameters.cache_key >>-{{ checksum "package-lock.json" }}
            - << parameters.cache_key >>
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: << parameters.cache_key >>-{{ checksum "package-lock.json" }}
      - run:
          name: Test
          command: npm test
      - run:
          name: Build
          command: npm run build

  command_save_workspace:
    steps:
      - persist_to_workspace:
          root: ~/bundlib
          paths:
            - .

  command_restore_workspace:
    steps:
      - attach_workspace:
          at: ~/bundlib

  command_npm_publish:
    steps:
      - run:
          name: Login to npm
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - run:
          name: Publish to npm
          command: npm publish

jobs:
  job_node_18_ci:
    executor: executor_node_18
    steps:
      - command_ci:
          cache_key: v8-node-18-deps-bundlib

  job_node_20_ci:
    executor: executor_node_20
    steps:
      - command_ci:
          cache_key: v8-node-20-deps-bundlib
      - command_save_workspace

  job_upload_coverage:
    executor: executor_node_20
    steps:
      - command_restore_workspace
      - codecov/upload:
          file: coverage/*.json

  job_publish_to_npm:
    executor: executor_node_20
    steps:
      - command_restore_workspace
      - command_npm_publish

workflows:
  workflow_ci:
    jobs:
      - job_node_18_ci:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/

      - job_node_20_ci:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/

      - job_upload_coverage:
          requires:
            - job_node_18_ci
            - job_node_20_ci
          filters:
            branches:
              only: /.*/
            tags:
              ignore: /.*/

      - job_publish_to_npm:
          context: npm
          requires:
            - job_node_18_ci
            - job_node_20_ci
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
