version: 2.1

orbs:
  codecov: codecov/codecov@4.1.0

executors:
  executor_node:
    docker:
      - image: cimg/node:20.15.1
    working_directory: ~/bundlib

commands:
  cmd_checkout_cache_and_install:
    steps:
      - checkout
      - restore_cache:
          keys:
            - v8-deps-bundlib-{{ checksum "package.json" }}
            - v8-deps-bundlib-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v8-deps-bundlib-{{ checksum "package.json" }}

  cmd_test_and_build:
    steps:
      - run:
          name: Test
          command: npm test
      - run:
          name: Build
          command: npm run build

  cmd_publish_to_npm:
    steps:
      - run:
          name: Login to npm
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - run:
          name: Publish to npm
          command: npm publish

jobs:
  job_test_and_build:
    executor: executor_node
    steps:
      - cmd_checkout_cache_and_install
      - cmd_test_and_build
      - persist_to_workspace:
          root: ~/bundlib
          paths:
            - bin/*
            - dist/*
            - coverage/*
            - src/*

  job_upload_coverage:
    executor: executor_node
    steps:
      - attach_workspace:
          at: ~/bundlib
      - codecov/upload:
          file: coverage/coverage-final.json

  job_publish_to_npm:
    executor: executor_node
    steps:
      - attach_workspace:
          at: ~/bundlib
      - cmd_publish_to_npm

workflows:
  workflow_ci:
    jobs:
      - job_test_and_build:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/

      - job_upload_coverage:
          requires:
            - job_test_and_build
          filters:
            branches:
              only: /master/

      - job_publish_to_npm:
          context: npm
          requires:
            - job_test_and_build
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
