version: 2.1

executors:

  node:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo

commands:
  npm-publish:
    steps:

      - run:
          name: Login to npm
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc

      - run:
          name: Publish to npm
          command: npm publish

jobs:

  unit-test:
    executor: node
    steps:

      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Test
          command: npm test

      - persist_to_workspace:
          root: ~/repo
          paths: .


  publish:
    executor: node
    steps:

      - attach_workspace:
          at: ~/repo

      - npm-publish

workflows:
  version: 2

  workflow:
    jobs:

      - unit-test:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/

      - publish:
          context: NPM
          requires:
            - unit-test
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
