/**
 * This file should contain all types derived from rollup types
 * ensuring the the objects generated by bundlib will be compatible
 * with rollup.
 */

import type { RollupOptions, OutputOptions as RollupOutputOptions } from 'rollup'
import type { ExcludeStrict, ExtractStrict } from '../../types/helper-types'

// Option input

type Rollup_InputOption = RollupOptions['input']
export type BundlibInputOption = ExtractStrict<Rollup_InputOption, string>

// Option output.sourcemap

type Rollup_SourcemapOption = NonNullable<RollupOutputOptions['sourcemap']>
export type BundlibSourcemapOption = ExtractStrict<Rollup_SourcemapOption, 'inline' | 'hidden' | boolean>
export type BundlibNonBooleanSourcemapOption = ExcludeStrict<BundlibSourcemapOption, boolean>

// Option output.esModule

type Rollup_ESModuleOption = NonNullable<RollupOutputOptions['esModule']>
export type BundlibESModuleOption = ExtractStrict<Rollup_ESModuleOption, 'if-default-prop' | boolean>
export type BundlibNonBooleanESModuleOption = ExcludeStrict<BundlibESModuleOption, boolean>

// Option output.interop

type Rollup_InteropOption = NonNullable<RollupOutputOptions['interop']>
export type BundlibNonBooleanInteropOption = ExtractStrict<Rollup_InteropOption, 'auto' | 'compat' | 'default' | 'defaultOnly' | 'esModule'>
export type BundlibInteropOption = BundlibNonBooleanInteropOption | boolean

// Option output.format

type Rollup_OutputFormat = NonNullable<RollupOutputOptions['format']>
export type BundlibModuleFormat = ExtractStrict<Rollup_OutputFormat, 'cjs' | 'es'>
export type BundlibBrowserFormat = ExtractStrict<Rollup_OutputFormat, 'iife' | 'umd' | 'amd'>
export type BundlibOutputFormat = BundlibModuleFormat | BundlibBrowserFormat
